# Application Configuration
app:
  name: "Flipkart Search System"
  version: "1.0.0"
  environment: "development"
  debug: true

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30

# Database Configuration
database:
  type: "sqlite"
  url: "sqlite:///./data/db/flipkart.db"
  echo: false
  pool_size: 20
  max_overflow: 30

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  decode_responses: true

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  file: "./logs/app.log"
  max_size: "10MB"
  backup_count: 5

# Security Configuration
security:
  secret_key: "your-secret-key-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30

# Performance Configuration
performance:
  max_concurrent_requests: 100
  request_timeout: 30
  keep_alive: 2
  enable_gzip: true
  gzip_minimum_size: 1000

# Monitoring Configuration
monitoring:
  enable_metrics: true
  prometheus_port: 9090
  health_check_interval: 30
